Feat: Next Client with search
bitcoinsearch/bitcoinsearch-app pull request #69
Opened 2023-09-25 09:27 UTC by Emmanuel-Develops

2023-09-29 18:11 UTC, Extheoisah requested changes
Quite a big pr. A lot of commented and unused code bit looking good otherwise.

2023-09-29 18:11 UTC, Extheoisah commented on src/hooks/useGlobalHotkey.ts
> +// import useIsMac from "@/hooks/useIsMac";
remove

2023-09-29 18:11 UTC, Extheoisah commented on src/hooks/useIsInitialStateWithoutFilter.ts
> +  // if (state) {
remove if not needed

2023-09-29 18:11 UTC, Extheoisah commented on src/hooks/useIsMac.ts
> +const useIsMac = () => {
can't find where we're using this hook.

2023-09-29 18:11 UTC, Extheoisah commented on src/pages/api/elasticSearchProxy/autocomplete.ts
> +
we can delete this file if its not in use

2023-09-29 18:11 UTC, Extheoisah commented on src/pages/api/elasticSearchProxy/connector.ts
> +// const connector = new ElasticsearchAPIConnector({
remove if not needed

2023-09-29 18:11 UTC, Extheoisah commented on src/pages/api/elasticSearchProxy/search.ts
> +    // console.log("🚀 ~ file: search.ts:37 ~ handler ~ result:", result.hits.total)
remove console logs

2023-09-29 18:14 UTC, Emmanuel-Develops commented on src/components/customResults/CustomResults.jsx
> +  // results.forEach((result) => {
there's a grouping i did previously, still debating if that's necessary

2023-09-29 18:15 UTC, Emmanuel-Develops commented
@Extheoisah, yeah there is a lot of cleaning up to do as I mentioned earlier.
Wanted to get functionality out of the way first

2023-10-02 11:05 UTC, Emmanuel-Develops commented on src/components/customResults/Thumbnail.jsx
> +        <img src={thumbnailURL} alt="thumbnail" />
nextImage would want us to specify the domains in the `next.config.js`. It allows a maximum of 50 domains while we currently have 59.
I could use a wildcard to catch all domains but that defeats the purpose and it is not recommended

2023-10-02 12:41 UTC, Extheoisah commented on src/components/customResults/Result.jsx
> +  // removed onClickLink
Just this remaining and we can merge

2023-10-05 14:35 UTC, merged