feat: footer and menu
bitcoinsearch/bitcoinsearch-app pull request #88
Opened 2024-03-12 08:23 UTC by BalogunofAfrica

2024-03-15 14:20 UTC, Extheoisah commented
this is how it looks on my laptop. Padding at the bottom is too large
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/c57ea17c-560d-46e3-9302-c8c4c20c2c88)

2024-03-15 14:22 UTC, Extheoisah commented on src/components/appMenu/AppItem.tsx
> +    <p className="text-lg text-[#666666]">{title}</p>
let's define this color code in tailwind config so that its reusable

2024-03-15 14:23 UTC, Extheoisah commented on src/components/appMenu/index.tsx
> +    <div className="ml-10 mb-[1000px] py-5 rounded-2xl border border-[#BFBFBF] w-[402px]">
see here -> https://github.com/bitcoinsearch/bitcoinsearch-app/pull/88/files#r1526366668

2024-03-15 14:26 UTC, Extheoisah commented on src/components/footer/ResultFooter.tsx
> +    <footer className="bg-white bottom-0 text-left md:text-center w-full border-t border-[#BFBFBF] text-xs md:text-base 2xl:text-xl leading-normal">
see comment here https://github.com/bitcoinsearch/bitcoinsearch-app/pull/88/files#r1526366668

2024-03-18 09:00 UTC, BalogunofAfrica commented
> this is how it looks on my laptop. Padding at the bottom is too large. This is in the homepage. It looks good in the search results page ![image](https://private-user-images.githubusercontent.com/60826700/313224687-c57ea17c-560d-46e3-9302-c8c4c20c2c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTE2MDMsIm5iZiI6MTcxMDc1MTMwMywicGF0aCI6Ii82MDgyNjcwMC8zMTMyMjQ2ODctYzU3ZWExN2MtNTYwZC00NmUzLTkzMDItYzhjNGMyMGMyYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4NDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NDMyZjM0N2Y3YjE5MGRlZDljODJjN2MzOTQ4MGRhYzEyYjJhMDYxYzI3ZjMxMDJiOGE5OTY4MGQ5MGE3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RcnT2bT_CRSJFz9Qvc5K5JfUMheNLHjjKXHIDVhH5Q8)

It shouldn't render in the home page, just results page. I have fixed it

2024-03-19 10:18 UTC, Emmanuel-Develops requested changes
The mobile screen is different from what we have in the design.
Please address this.

2024-03-19 10:22 UTC, BalogunofAfrica commented
> The mobile screen is different from what we have in the design. Please address this.

Please check the new preview, forgot to push this earlier

2024-03-19 10:24 UTC, Emmanuel-Develops approved these changes
Looks good!

2024-03-19 10:25 UTC, merged