feat: dark mode
bitcoinsearch/bitcoinsearch-app pull request #99
Opened 2024-04-02 19:35 UTC by BalogunofAfrica

Add dark mode support

Note: I did not touch the results page itself since that's going through some sort of redesign itself

2024-04-02 20:04 UTC, Extheoisah commented
Some comments when I compared with the [figma dark mode design](https://www.figma.com/file/d43NNG3nVnDQcuvloueVbD/BTC-SEARCH-Product?type=design&node-id=75-9109&mode=design&t=xALDa4b1Go27chnp-0).

1. You need to use the homepage images for dark mode in the design.
2. (Not related to this pr) The app menu button doesn't have a title when you hover on it like is stated in the design
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/e85dbfc7-2352-42d9-a5f7-7c9e7205aac0)
3. The homepage arrow down icon border color should not be white but orange as stated in the design
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/0c753ead-dbb0-45ea-9511-eddd4ea1f983)
vs 
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/a9b5baeb-4f20-421c-a80c-b5d61bf3c618)
4. The search suggestion box isn't in dark mode.
<img width="900" alt="Screenshot 2024-04-02 at 21 03 08" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/4b7ee352-213d-4110-aeb2-0fd3f5faa435">

2024-04-03 09:26 UTC, Emmanuel-Develops requested changes

2024-04-03 09:26 UTC, Emmanuel-Develops commented on src/styles/globals.css
> -  font-family: 'Geist Sans', sans-serif !important;
```suggestion
font-family: 'Geist Sans', sans-serif !important;
```
chakra-ui overwrites font-family body style. That's why its set to `!important`

2024-04-03 22:54 UTC, Extheoisah approved these changes
Looks good!

2024-04-03 22:54 UTC, merged